// src/utils/auditStore.js
/**
 * GlycoGourmet Immutable Audit Log Store (v0.2)
 *
 * Enforces an append-only audit trail for all Clinic Administrator mutations
 * (intake stage updates, dietitian assignments, tier routing, promotions, and disputes).
 *
 * Immutability Guarantee:
 * This module exposes only append and query operations. No mutation (update) or
 * deletion interfaces exist.
 *
 * FHIR / LOINC Isolation Boundary:
 * Non-clinical audit object â€” strictly excluded from metabolic telemetry pipelines.
 */

const STORAGE_KEY = 'glyco_audit_log_entries';
let inMemoryLogs = [];

/**
 * Reads all audit log entries from storage.
 */
export const getAllAuditLogs = () => {
  if (typeof localStorage === 'undefined') {
    return inMemoryLogs.map((entry) => Object.freeze({ ...entry }));
  }
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const entries = JSON.parse(raw);
    return entries.map((entry) => Object.freeze({ ...entry }));
  } catch (err) {
    console.error('[auditStore] Error reading audit logs:', err);
    return [];
  }
};

/**
 * Appends a new immutable AuditLogEntry to the store.
 */
export const logAdminAction = ({
  actorId,
  actorRole = 'clinic_admin',
  action,
  entityId,
  entityType = 'referral_lead',
  suggestedValue = null,
  finalValue,
  note = '',
}) => {
  if (!actorId || !action || !entityId) {
    throw new Error('[auditStore] actorId, action, and entityId are required to record an audit log');
  }

  const newEntry = Object.freeze({
    id: `audit_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
    actorId,
    actorRole,
    action,
    entityId,
    entityType,
    suggestedValue,
    finalValue,
    note: String(note || ''),
    timestamp: new Date().toISOString(),
  });

  const existing = getAllAuditLogs();
  const updated = [newEntry, ...existing];

  inMemoryLogs = updated;

  if (typeof localStorage !== 'undefined') {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    } catch (err) {
      console.error('[auditStore] Error persisting audit entry:', err);
    }
  }

  if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function') {
    try {
      window.dispatchEvent(new CustomEvent('glyco:audit:created', { detail: { entry: newEntry } }));
    } catch (_e) {
      // Ignore in non-browser environments
    }
  }

  return newEntry;
};

/**
 * Queries audit entries for a specific entity ID.
 */
export const getAuditLogsForEntity = (entityId) => {
  if (!entityId) return [];
  const logs = getAllAuditLogs();
  return logs.filter((entry) => entry.entityId === entityId);
};

/**
 * Queries audit entries generated by a specific actor ID.
 */
export const getAuditLogsByActor = (actorId) => {
  if (!actorId) return [];
  const logs = getAllAuditLogs();
  return logs.filter((entry) => entry.actorId === actorId);
};

/**
 * Clears the audit log store (strictly for testing setup/teardown).
 */
export const clearAuditStore = () => {
  inMemoryLogs = [];
  if (typeof localStorage !== 'undefined') {
    localStorage.removeItem(STORAGE_KEY);
  }
};