/**
 * exportPipeline.js
 * Clinical export utilities for Grocery Manifests, PDF Reports, and FHIR Telemetry.
 */
import { calculateRecipeNutrition } from './nutritionCalculator';

const CATEGORY_MAP = {
  produce: ['vegetable', 'fruit', 'herb'],
  proteins: ['meat', 'poultry', 'seafood', 'legume'],
  dairy: ['dairy', 'cheese', 'egg'],
  pantry: ['grain', 'spice', 'oil', 'nut', 'baking', 'condiment', 'sweetener'],
};

export const generateGroceryManifest = (planMatrix, recipesMap, ingredientsMap = {}) => {
  const aggregated = {};

  Object.values(planMatrix).forEach(slot => {
    if (!slot || !slot.recipeId || !recipesMap[slot.recipeId]) return;
    const recipe = recipesMap[slot.recipeId];
    const multiplier = slot.multiplier || 1;

    (recipe.ingredients || []).forEach(item => {
      // Handle missing ingredient payloads gracefully
      const baseId = item.ingredientId || item.ingredient?.id || 'unknown';
      const amount = (item.amount || 0) * multiplier;
      const unit = item.unit || 'g';
      
      const ingDef = item.ingredient || ingredientsMap[baseId] || { name: baseId, category: 'pantry' };
      const name = ingDef.name || baseId;
      const categoryRaw = (ingDef.category || 'pantry').toLowerCase();
      
      let mappedCategory = 'pantry';
      for (const [key, tags] of Object.entries(CATEGORY_MAP)) {
        if (tags.some(t => categoryRaw.includes(t))) {
          mappedCategory = key;
          break;
        }
      }

      if (!aggregated[mappedCategory]) aggregated[mappedCategory] = {};
      if (!aggregated[mappedCategory][name]) {
        aggregated[mappedCategory][name] = { amount: 0, unit };
      }
      aggregated[mappedCategory][name].amount += amount;
    });
  });

  const result = { produce: [], proteins: [], dairy: [], pantry: [] };
  Object.keys(aggregated).forEach(cat => {
    if (result[cat]) {
      Object.entries(aggregated[cat]).forEach(([name, data]) => {
        result[cat].push({ name, amount: Math.round(data.amount * 10) / 10, unit: data.unit });
      });
    }
  });

  return result;
};

export const generateClinicalSummaryReport = (clientProfile, calibration, planMatrix, recipesMap, dailyRollups) => {
  let report = `CLINICAL METABOLIC SUMMARY\n`;
  report += `=========================================\n`;
  report += `Patient: ${clientProfile?.name || 'Unknown'}\n`;
  report += `Subtype: ${clientProfile?.diabeticSubtype || 'Unspecified'}\n`;
  report += `Daily GL Target: ${calibration?.glTargetDaily || 0}\n\n`;
  
  report += `DAILY ROLLUPS:\n`;
  const DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
  DAYS.forEach(day => {
    const rollup = dailyRollups[day] || { cumulativeDailyGL: 0, netCarbs: 0, protein: 0, fat: 0, fiber: 0 };
    report += `- ${day.toUpperCase()}: GL ${rollup.cumulativeDailyGL} | NC ${rollup.netCarbs}g | Pro ${rollup.protein}g | Fat ${rollup.fat}g | Fib ${rollup.fiber}g\n`;
  });

  report += `\n=========================================\n`;
  report += `Generated by GlycoGourmet Clinical Engine`;
  return report;
};

export const exportFHIRMetabolicTelemetry = (clientProfile, planMatrix, dailyRollups) => {
  const patientId = clientProfile?.patientUserId || clientProfile?.id || 'unknown';
  const bundle = {
    resourceType: 'Bundle',
    type: 'collection',
    entry: []
  };

  const DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
  
  DAYS.forEach((day, index) => {
    const rollup = dailyRollups[day] || { cumulativeDailyGL: 0, netCarbs: 0 };
    const date = new Date();
    date.setDate(date.getDate() + index);

    // Carbs Observation
    bundle.entry.push({
      fullUrl: `urn:uuid:carb-${day}-${Date.now()}`,
      resource: {
        resourceType: 'Observation',
        status: 'final',
        category: [{ coding: [{ system: 'http://terminology.hl7.org/CodeSystem/observation-category', code: 'nutrition' }] }],
        code: { coding: [{ system: 'http://loinc.org', code: '9843-4', display: 'Carbohydrate intake' }] },
        subject: { reference: `Patient/${patientId}` },
        effectiveDateTime: date.toISOString().split('T')[0],
        valueQuantity: { value: rollup.netCarbs, unit: 'g', system: 'http://unitsofmeasure.org', code: 'g' }
      }
    });

    // GL Observation (Custom)
    bundle.entry.push({
      fullUrl: `urn:uuid:gl-${day}-${Date.now()}`,
      resource: {
        resourceType: 'Observation',
        status: 'final',
        category: [{ coding: [{ system: 'http://terminology.hl7.org/CodeSystem/observation-category', code: 'nutrition' }] }],
        code: { coding: [{ system: 'http://glycogourmet.com/codes', code: 'GL-DAILY', display: 'Daily Glycemic Load' }] },
        subject: { reference: `Patient/${patientId}` },
        effectiveDateTime: date.toISOString().split('T')[0],
        valueQuantity: { value: rollup.cumulativeDailyGL, unit: '{GL}', system: 'http://unitsofmeasure.org', code: '{GL}' }
      }
    });
  });

  return bundle;
};
